### PR TITLE
Updating to unified 0.17 cuda 11.0 container

### PR DESCRIPTION
**Pull request by miroenev**
Known not to work with given container size. 
Will retest when container image is reduced.

### CODE REVIEW

**Review by drobison00 — APPROVED** [review]
Looks good.

**Comment by drobison00** [comment]
@miroenev anything new on this? Since we're going to have to do it again for 0.18 now :)?

**Comment by zronaghi** [comment]
Tracking image size and updates at #60

**Comment by zronaghi** [comment]
@miroenev can we close this? Since you're working on it with #84

**Pull request closed without merging**
