### PR TITLE
Specifying ucx-proc in environments.

### LINKED ISSUE #163: Include `ucx-proc=*=gpu`
Looks like there are a few environment files specifying `ucx` & `ucx-py` here that don't also specify `ucx-proc`. While the very tight pinning likely enforces `ucx-proc=*=gpu` indirectly, it would be good to include it explicitly as well. This would also be helpful if the pinnings are relaxed in the future.

### PR DESCRIPTION
**Pull request by mmccarty**
closes #163 
cc @jakirkham

### CODE REVIEW

**Review by jakirkham — APPROVED** [review]
Thanks Mike! 🙏

**Comment by mmccarty** [comment]
@jacobtomlinson @jarmak-nv - I think one of you has write access, could you please take a look and approve if it looks good?
@jakirkham - Thanks! You might want to get that for this repo.

**Review by jacobtomlinson — APPROVED** [review]

**Comment by jacobtomlinson** [comment]
I don't seem to have write access yet, but it looks good to me!

**Comment by mmccarty** [comment]
Ah, okay thanks. @ajschmidt8 can you approve?

**Review by ajschmidt8 — APPROVED** [review]

**Pull request merged**
