### PR TITLE
[IN PROGRESS] Update cuML API

### PR DESCRIPTION
**Pull request by sarahyurick**
starting to locate and update hardcoded RAPIDS versions and outdated usages (i.e., `train_test_split`)
- not including any databricks files

### CODE REVIEW

**Comment by zronaghi** [comment]
@sarahyurick thanks! Is this ready for review?

**Comment by sarahyurick** [comment]
yes, the only examples I didn't update were: 
- mlflow/local_environment/notebooks/databricks_mlflow_rapids.ipynb
- databricks/notebooks/rapids_airline_hyperopt.ipynb
Since they are related to Databricks. 

also for reference, I generated a list of all files with the RAPIDS version hardcoded (e.g. if a file contains the string '21.06', 'rapidsai:0.19', etc.). 

[hardcoded_rapids.txt](https://github.com/rapidsai/cloud-ml-examples/files/6710975/hardcoded_rapids.txt)

I haven't updated any of the version numbers, though

**Comment by zronaghi** [comment]
Great we can leave the other two notebooks since those are based on previous DB setup, and that file is useful :)

**Comment by sarahyurick** [comment]
ok, should I start updating any of the RAPIDS versions or just leave as is for now?

**Comment by zronaghi** [comment]
Can you open another PR to update the RAPIDS versions, this one should be good to go

**Review by zronaghi — APPROVED** [review]

**Pull request merged**
